language: node_js
node_js:
    - "8"
    - "7"
    - "6"
deploy:
  provider: s3
  access_key_id: AKIAJWMKWOHSHPFJ7XAQ
  secret_access_key: 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
  bucket: sewemark-deploy-web
  upload-dir: server
  acl: ''
  on:
    repo: sewemark/aws-nodejs-images-app
